SELECT [ID], [NAME], [DESCRIPTION] 
FROM [PRODUCT_BRANDS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_PRODUCT_BRANDS_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 