SELECT PB.[ID], PB.[NAME], PB.[DESCRIPTION], PB.[LOGO_URL], PB.[IS_ACTIVE] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_BRANDS] PB 
			ON P.[BRAND_ID] = PB.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PB.[IsDeleted] = 0 
	AND PB.[ID] = @PRM_PRODUCT_BRANDS_ID 
ORDER BY PB.[ID] 