SELECT P.[ID], P.[NAME], P.[DESCRIPTION], P.[SKU], P.[PRICE], P.[CATEGORY_ID], P.[BRAND_ID], P.[STATUS], P.[VISIBILITY], P.[CREATED_DATE] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_BRANDS] PB 
			ON P.[BRAND_ID] = PB.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PB.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PRODUCTS_ID 
	AND PB.[ID] = @PRM_PRODUCT_BRANDS_ID 
ORDER BY P.[ID] 