SELECT [ID], [NAME], [DESCRIPTION] 
FROM [PRODUCT_BRANDS] 
WHERE [IsDeleted] = 0 
	AND [NAME] LIKE '%' + @PRM_PRODUCT_BRANDS_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 