//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ProductCatalogModule.Persistence.Contexts;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.Product;
using QuickCode.DemoTest.ProductCatalogModule.Application.Mappings;
using QuickCode.DemoTest.ProductCatalogModule.Persistence.Sql;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductRepository : BaseRepository, IProductRepository
    {
        public async Task<RepoResponse<int>> UpdatePriceAsync(int productsId, UpdatePriceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Product", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.UpdatePrice);
                var parameters = new
                {
                    PRODUCTS_PRICE = updateRequest.ProductsPrice,
                    PRM_PRODUCTS_ID = productsId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}