//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.IdentityModule.Domain.Entities;
using QuickCode.DemoTest.IdentityModule.Application.Dtos.AspNetUserLogin;
using System.Threading.Tasks;
using QuickCode.DemoTest.IdentityModule.Domain.Enums;

namespace QuickCode.DemoTest.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IAspNetUserLoginRepository : IBaseRepository<AspNetUserLoginDto>
    {
        Task<RepoResponse<AspNetUserLoginDto>> GetByPkAsync(string loginProvider, string providerKey);
    }
}