//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.IdentityModule.Domain.Entities;
using QuickCode.DemoTest.IdentityModule.Application.Dtos.PortalPageDefinition;
using System.Threading.Tasks;
using QuickCode.DemoTest.IdentityModule.Domain.Enums;

namespace QuickCode.DemoTest.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IPortalPageDefinitionRepository : IBaseRepository<PortalPageDefinitionDto>
    {
        Task<RepoResponse<PortalPageDefinitionDto>> GetByPkAsync(string key);
        Task<RepoResponse<List<GetPortalPageDefinitionsWithModuleNameResponseDto>>> GetPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionsModuleName);
        Task<RepoResponse<List<GetPortalPageDefinitionsWithModelNameResponseDto>>> GetPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionsModelName);
        Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionsModuleName);
        Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionsModelName);
        Task<RepoResponse<List<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>>> GetPortalPageAccessGrantsForPortalPageDefinitionsAsync(string portalPageDefinitionsKey);
        Task<RepoResponse<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>> GetPortalPageAccessGrantsForPortalPageDefinitionsDetailsAsync(string portalPageDefinitionsKey, string portalPageAccessGrantsPermissionGroupName);
        Task<RepoResponse<int>> DeletePortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionsModuleName);
        Task<RepoResponse<int>> DeletePortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionsModelName);
    }
}