//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.OrderModule.Application.Dtos.Order;
using QuickCode.DemoTest.OrderModule.Domain.Entities;
using QuickCode.DemoTest.OrderModule.Domain.Enums;

namespace QuickCode.DemoTest.OrderModule.Application.Mappings
{
    public static class OrderMappings
    {
        public static List<OrderDto> ToDto(this IEnumerable<Order> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderDto ToDto(this Order model)
        {
            return new OrderDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                OrderDate = model.OrderDate,
                TotalAmount = model.TotalAmount,
                ShippingAddressId = model.ShippingAddressId,
                BillingAddressId = model.BillingAddressId,
                OrderStatus = model.OrderStatus,
                PaymentStatus = model.PaymentStatus,
                PaymentMethodId = model.PaymentMethodId,
                CreatedDate = model.CreatedDate
            };
        }

        public static Order ToEntity(this OrderDto model)
        {
            return new Order
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                OrderDate = model.OrderDate,
                TotalAmount = model.TotalAmount,
                ShippingAddressId = model.ShippingAddressId,
                BillingAddressId = model.BillingAddressId,
                OrderStatus = model.OrderStatus,
                PaymentStatus = model.PaymentStatus,
                PaymentMethodId = model.PaymentMethodId,
                CreatedDate = model.CreatedDate
            };
        }
    }
}