//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.OrderModule.Application.Dtos.ShippingAddress;
using QuickCode.DemoTest.OrderModule.Domain.Entities;
using QuickCode.DemoTest.OrderModule.Domain.Enums;

namespace QuickCode.DemoTest.OrderModule.Application.Mappings
{
    public static class ShippingAddressMappings
    {
        public static List<ShippingAddressDto> ToDto(this IEnumerable<ShippingAddress> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ShippingAddressDto ToDto(this ShippingAddress model)
        {
            return new ShippingAddressDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                AddressLine1 = model.AddressLine1,
                AddressLine2 = model.AddressLine2,
                City = model.City,
                State = model.State,
                ZipCode = model.ZipCode,
                Country = model.Country
            };
        }

        public static ShippingAddress ToEntity(this ShippingAddressDto model)
        {
            return new ShippingAddress
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                AddressLine1 = model.AddressLine1,
                AddressLine2 = model.AddressLine2,
                City = model.City,
                State = model.State,
                ZipCode = model.ZipCode,
                Country = model.Country
            };
        }
    }
}