//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ProductCatalogModule.Persistence.Contexts;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductBrand;
using QuickCode.DemoTest.ProductCatalogModule.Application.Mappings;
using QuickCode.DemoTest.ProductCatalogModule.Persistence.Sql;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductBrandRepository : BaseRepository, IProductBrandRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool productBrandsIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ProductBrand.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRODUCT_BRANDS_IS_ACTIVE = productBrandsIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ProductBrand");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string productBrandsName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("SearchByName", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ProductBrand.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRODUCT_BRANDS_NAME = productBrandsName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ProductBrand");
                }
            });
        }

        public async Task<RepoResponse<List<GetProductsForProductBrandsResponseDto>>> GetProductsForProductBrandsAsync(int productBrandsId)
        {
            return await ExecuteWithExceptionHandling("GetProductsForProductBrands", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductBrand.Query.GetProductsForProductBrands);
                var parameters = new
                {
                    PRM_PRODUCT_BRANDS_ID = productBrandsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetProductsForProductBrandsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ProductBrand");
            });
        }

        public async Task<RepoResponse<GetProductsForProductBrandsResponseDto>> GetProductsForProductBrandsDetailsAsync(int productBrandsId, int productsId)
        {
            return await ExecuteWithExceptionHandling("GetProductsForProductBrandsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductBrand.Query.GetProductsForProductBrandsDetails);
                var parameters = new
                {
                    PRM_PRODUCTS_ID = productsId,
                    PRM_PRODUCT_BRANDS_ID = productBrandsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetProductsForProductBrandsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProductBrand");
            });
        }
    }
}