//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ShippingModule.Persistence.Contexts;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.Shipment;
using QuickCode.DemoTest.ShippingModule.Application.Mappings;
using QuickCode.DemoTest.ShippingModule.Persistence.Sql;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Persistence.Repositories
{
    public partial class ShipmentRepository : BaseRepository, IShipmentRepository
    {
        public async Task<RepoResponse<List<GetByOrderResponseDto>>> GetByOrderAsync(int shipmentsOrderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByOrder", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByOrderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetByOrder);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENTS_ORDER_ID = shipmentsOrderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByOrderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Shipment");
                }
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ShippingStatus shipmentsShippingStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENTS_SHIPPING_STATUS = shipmentsShippingStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Shipment");
                }
            });
        }

        public async Task<RepoResponse<List<GetShipmentTrackingEventsForShipmentsResponseDto>>> GetShipmentTrackingEventsForShipmentsAsync(int shipmentsId)
        {
            return await ExecuteWithExceptionHandling("GetShipmentTrackingEventsForShipments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetShipmentTrackingEventsForShipments);
                var parameters = new
                {
                    PRM_SHIPMENTS_ID = shipmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetShipmentTrackingEventsForShipmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Shipment");
            });
        }

        public async Task<RepoResponse<GetShipmentTrackingEventsForShipmentsResponseDto>> GetShipmentTrackingEventsForShipmentsDetailsAsync(int shipmentsId, int shipmentTrackingEventsId)
        {
            return await ExecuteWithExceptionHandling("GetShipmentTrackingEventsForShipmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetShipmentTrackingEventsForShipmentsDetails);
                var parameters = new
                {
                    PRM_SHIPMENT_TRACKING_EVENTS_ID = shipmentTrackingEventsId,
                    PRM_SHIPMENTS_ID = shipmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetShipmentTrackingEventsForShipmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Shipment");
            });
        }

        public async Task<RepoResponse<List<GetDeliveryExceptionsForShipmentsResponseDto>>> GetDeliveryExceptionsForShipmentsAsync(int shipmentsId)
        {
            return await ExecuteWithExceptionHandling("GetDeliveryExceptionsForShipments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetDeliveryExceptionsForShipments);
                var parameters = new
                {
                    PRM_SHIPMENTS_ID = shipmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetDeliveryExceptionsForShipmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Shipment");
            });
        }

        public async Task<RepoResponse<GetDeliveryExceptionsForShipmentsResponseDto>> GetDeliveryExceptionsForShipmentsDetailsAsync(int shipmentsId, int deliveryExceptionsId)
        {
            return await ExecuteWithExceptionHandling("GetDeliveryExceptionsForShipmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Shipment.Query.GetDeliveryExceptionsForShipmentsDetails);
                var parameters = new
                {
                    PRM_DELIVERY_EXCEPTIONS_ID = deliveryExceptionsId,
                    PRM_SHIPMENTS_ID = shipmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetDeliveryExceptionsForShipmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Shipment");
            });
        }
    }
}