//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ShippingModule.Persistence.Contexts;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.Shipment;
using QuickCode.DemoTest.ShippingModule.Application.Mappings;
using QuickCode.DemoTest.ShippingModule.Persistence.Sql;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Persistence.Repositories
{
    public partial class ShipmentRepository : BaseRepository, IShipmentRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int shipmentsId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Shipment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Shipment.Command.UpdateStatus);
                var parameters = new
                {
                    SHIPMENTS_SHIPPING_STATUS = updateRequest.ShipmentsShippingStatus,
                    PRM_SHIPMENTS_ID = shipmentsId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}