SELECT [ID], [NAME], [CONTACT_NAME], [CONTACT_EMAIL], [CONTACT_PHONE] 
FROM [SUPPLIERS] 
WHERE [IsDeleted] = 0 
	AND [NAME] LIKE '%' + @PRM_SUPPLIERS_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 