//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.OrderModule.Domain.Entities;
using QuickCode.DemoTest.OrderModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.OrderModule.Persistence.Contexts;
using QuickCode.DemoTest.OrderModule.Application.Dtos.BillingAddress;
using QuickCode.DemoTest.OrderModule.Application.Mappings;
using QuickCode.DemoTest.OrderModule.Persistence.Sql;
using QuickCode.DemoTest.OrderModule.Domain.Enums;

namespace QuickCode.DemoTest.OrderModule.Persistence.Repositories
{
    public partial class BillingAddressRepository : BaseRepository, IBillingAddressRepository
    {
        public async Task<RepoResponse<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int billingAddressesCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByCustomer", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.BillingAddress.Query.GetByCustomer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_BILLING_ADDRESSES_CUSTOMER_ID = billingAddressesCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByCustomerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in BillingAddress");
                }
            });
        }

        public async Task<RepoResponse<List<GetOrdersForBillingAddressesResponseDto>>> GetOrdersForBillingAddressesAsync(int billingAddressesId)
        {
            return await ExecuteWithExceptionHandling("GetOrdersForBillingAddresses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.BillingAddress.Query.GetOrdersForBillingAddresses);
                var parameters = new
                {
                    PRM_BILLING_ADDRESSES_ID = billingAddressesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetOrdersForBillingAddressesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in BillingAddress");
            });
        }

        public async Task<RepoResponse<GetOrdersForBillingAddressesResponseDto>> GetOrdersForBillingAddressesDetailsAsync(int billingAddressesId, int ordersId)
        {
            return await ExecuteWithExceptionHandling("GetOrdersForBillingAddressesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.BillingAddress.Query.GetOrdersForBillingAddressesDetails);
                var parameters = new
                {
                    PRM_ORDERS_ID = ordersId,
                    PRM_BILLING_ADDRESSES_ID = billingAddressesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOrdersForBillingAddressesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in BillingAddress");
            });
        }
    }
}