SELECT W.[ID], W.[NAME], W.[LOCATION], W.[IS_ACTIVE] 
FROM [INVENTORY_ADJUSTMENTS] IA 
	INNER JOIN [WAREHOUSES] W 
			ON IA.[WAREHOUSE_ID] = W.[ID] 
WHERE IA.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY W.[ID] 