SELECT IA.[ID], IA.[PRODUCT_ID], IA.[WAREHOUSE_ID], IA.[ADJUSTMENT_QUANTITY], IA.[ADJUSTMENT_REASON], IA.[ADJUSTMENT_DATE] 
FROM [INVENTORY_ADJUSTMENTS] IA 
	INNER JOIN [WAREHOUSES] W 
			ON IA.[WAREHOUSE_ID] = W.[ID] 
WHERE IA.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND IA.[ID] = @PRM_INVENTORY_ADJUSTMENTS_ID 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY IA.[ID] 