SELECT W.[ID], W.[NAME], W.[LOCATION], W.[IS_ACTIVE] 
FROM [REORDER_POINTS] RP 
	INNER JOIN [WAREHOUSES] W 
			ON RP.[WAREHOUSE_ID] = W.[ID] 
WHERE RP.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY W.[ID] 