SELECT RP.[ID], RP.[PRODUCT_ID], RP.[WAREHOUSE_ID], RP.[REORDER_QUANTITY], RP.[MINIMUM_STOCK_LEVEL] 
FROM [REORDER_POINTS] RP 
	INNER JOIN [WAREHOUSES] W 
			ON RP.[WAREHOUSE_ID] = W.[ID] 
WHERE RP.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND RP.[ID] = @PRM_REORDER_POINTS_ID 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY RP.[ID] 