SELECT W.[ID], W.[NAME], W.[LOCATION], W.[IS_ACTIVE] 
FROM [STOCKS] S 
	INNER JOIN [WAREHOUSES] W 
			ON S.[WAREHOUSE_ID] = W.[ID] 
WHERE S.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY W.[ID] 