SELECT S.[ID], S.[PRODUCT_ID], S.[WAREHOUSE_ID], S.[QUANTITY], S.[LAST_UPDATED] 
FROM [STOCKS] S 
	INNER JOIN [WAREHOUSES] W 
			ON S.[WAREHOUSE_ID] = W.[ID] 
WHERE S.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND S.[ID] = @PRM_STOCKS_ID 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY S.[ID] 