SELECT W.[ID], W.[NAME], W.[LOCATION], W.[IS_ACTIVE] 
FROM [STOCK_MOVEMENTS] SM 
	INNER JOIN [WAREHOUSES] W 
			ON SM.[WAREHOUSE_ID] = W.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY W.[ID] 