SELECT SM.[ID], SM.[PRODUCT_ID], SM.[WAREHOUSE_ID], SM.[MOVEMENT_TYPE], SM.[QUANTITY], SM.[MOVEMENT_DATE] 
FROM [STOCK_MOVEMENTS] SM 
	INNER JOIN [WAREHOUSES] W 
			ON SM.[WAREHOUSE_ID] = W.[ID] 
WHERE SM.[IsDeleted] = 0 
	AND W.[IsDeleted] = 0 
	AND SM.[ID] = @PRM_STOCK_MOVEMENTS_ID 
	AND W.[ID] = @PRM_WAREHOUSES_ID 
ORDER BY SM.[ID] 