//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.OrderModule.Domain.Enums;

namespace QuickCode.DemoTest.OrderModule.Application.Dtos.PaymentMethod
{
    public record PaymentMethodDto
    {
        public int Id { get; init; }
        public int CustomerId { get; init; }
        public string CardNumber { get; init; }
        public DateTime ExpiryDate { get; init; }
        public string Cvv { get; init; }
        public string PaymentType { get; init; }
    }
}