SELECT O.[ID], O.[CUSTOMER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[SHIPPING_ADDRESS_ID], O.[BILLING_ADDRESS_ID], O.[ORDER_STATUS], O.[PAYMENT_STATUS], O.[PAYMENT_METHOD_ID], O.[CREATED_DATE] 
FROM [ORDERS] O 
	INNER JOIN [BILLING_ADDRESSES] BA 
			ON O.[BILLING_ADDRESS_ID] = BA.[ID] 
WHERE O.[IsDeleted] = 0 
	AND BA.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND BA.[ID] = @PRM_BILLING_ADDRESSES_ID 
ORDER BY O.[ID] 