SELECT BA.[ID], BA.[CUSTOMER_ID], BA.[ADDRESS_LINE_1], BA.[ADDRESS_LINE_2], BA.[CITY], BA.[STATE], BA.[ZIP_CODE], BA.[COUNTRY] 
FROM [ORDERS] O 
	INNER JOIN [BILLING_ADDRESSES] BA 
			ON O.[BILLING_ADDRESS_ID] = BA.[ID] 
WHERE O.[IsDeleted] = 0 
	AND BA.[IsDeleted] = 0 
	AND BA.[ID] = @PRM_BILLING_ADDRESSES_ID 
ORDER BY BA.[ID] 