SELECT [ID], [WAREHOUSE_ID], [MOVEMENT_TYPE], [QUANTITY], [MOVEMENT_DATE] 
FROM [STOCK_MOVEMENTS] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_STOCK_MOVEMENTS_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 