SELECT PR.[ID], PR.[PRODUCT_ID], PR.[USER_ID], PR.[RATING], PR.[COMMENT], PR.[CREATED_DATE] 
FROM [PRODUCT_REVIEWS] PR 
	INNER JOIN [PRODUCTS] P 
			ON PR.[PRODUCT_ID] = P.[ID] 
WHERE PR.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND PR.[ID] = @PRM_PRODUCT_REVIEWS_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY PR.[ID] 