SELECT P.[ID], P.[NAME], P.[DESCRIPTION], P.[SKU], P.[PRICE], P.[CATEGORY_ID], P.[BRAND_ID], P.[STATUS], P.[VISIBILITY], P.[CREATED_DATE] 
FROM [PRODUCT_REVIEWS] PR 
	INNER JOIN [PRODUCTS] P 
			ON PR.[PRODUCT_ID] = P.[ID] 
WHERE PR.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY P.[ID] 