SELECT PS.[ID], PS.[PRODUCT_ID], PS.[SPECIFICATION_KEY], PS.[SPECIFICATION_VALUE] 
FROM [PRODUCT_SPECIFICATIONS] PS 
	INNER JOIN [PRODUCTS] P 
			ON PS.[PRODUCT_ID] = P.[ID] 
WHERE PS.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND PS.[ID] = @PRM_PRODUCT_SPECIFICATIONS_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY PS.[ID] 