SELECT PI.[ID], PI.[PRODUCT_ID], PI.[IMAGE_URL], PI.[IS_PRIMARY] 
FROM [PRODUCT_IMAGES] PI 
	INNER JOIN [PRODUCTS] P 
			ON PI.[PRODUCT_ID] = P.[ID] 
WHERE PI.[IsDeleted] = 0 
	AND P.[IsDeleted] = 0 
	AND PI.[ID] = @PRM_PRODUCT_IMAGES_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY PI.[ID] 