SELECT [ID], [NAME], [PRICE], [CATEGORY_ID] 
FROM [PRODUCTS] 
WHERE [IsDeleted] = 0 
	AND [NAME] LIKE '%' + @PRM_PRODUCTS_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 