SELECT [ID], [WEIGHT_FROM], [WEIGHT_TO], [RATE] 
FROM [SHIPPING_RATES] 
WHERE [IsDeleted] = 0 
	AND [CARRIER_ID] = @PRM_SHIPPING_RATES_CARRIER_ID 
	AND [DESTINATION_ZIP_CODE] = @PRM_SHIPPING_RATES_DESTINATION_ZIP_CODE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 