SELECT [ID], [WAREHOUSE_ID], [ADJUSTMENT_QUANTITY], [ADJUSTMENT_REASON], [ADJUSTMENT_DATE] 
FROM [INVENTORY_ADJUSTMENTS] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_INVENTORY_ADJUSTMENTS_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 