SELECT [ID], [USER_ID], [RATING], [COMMENT] 
FROM [PRODUCT_REVIEWS] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_PRODUCT_REVIEWS_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 