//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.InventoryModule.Application.Dtos.InventoryAdjustment;
using QuickCode.DemoTest.InventoryModule.Domain.Entities;

namespace QuickCode.DemoTest.InventoryModule.Application.Mappings
{
    public static class InventoryAdjustmentMappings
    {
        public static List<InventoryAdjustmentDto> ToDto(this IEnumerable<InventoryAdjustment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static InventoryAdjustmentDto ToDto(this InventoryAdjustment model)
        {
            return new InventoryAdjustmentDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                WarehouseId = model.WarehouseId,
                AdjustmentQuantity = model.AdjustmentQuantity,
                AdjustmentReason = model.AdjustmentReason,
                AdjustmentDate = model.AdjustmentDate
            };
        }

        public static InventoryAdjustment ToEntity(this InventoryAdjustmentDto model)
        {
            return new InventoryAdjustment
            {
                Id = model.Id,
                ProductId = model.ProductId,
                WarehouseId = model.WarehouseId,
                AdjustmentQuantity = model.AdjustmentQuantity,
                AdjustmentReason = model.AdjustmentReason,
                AdjustmentDate = model.AdjustmentDate
            };
        }
    }
}