//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.InventoryModule.Application.Dtos.Stock;
using QuickCode.DemoTest.InventoryModule.Domain.Entities;

namespace QuickCode.DemoTest.InventoryModule.Application.Mappings
{
    public static class StockMappings
    {
        public static List<StockDto> ToDto(this IEnumerable<Stock> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static StockDto ToDto(this Stock model)
        {
            return new StockDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                WarehouseId = model.WarehouseId,
                Quantity = model.Quantity,
                LastUpdated = model.LastUpdated
            };
        }

        public static Stock ToEntity(this StockDto model)
        {
            return new Stock
            {
                Id = model.Id,
                ProductId = model.ProductId,
                WarehouseId = model.WarehouseId,
                Quantity = model.Quantity,
                LastUpdated = model.LastUpdated
            };
        }
    }
}