//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.InventoryModule.Application.Dtos.Warehouse;
using QuickCode.DemoTest.InventoryModule.Domain.Entities;

namespace QuickCode.DemoTest.InventoryModule.Application.Mappings
{
    public static class WarehouseMappings
    {
        public static List<WarehouseDto> ToDto(this IEnumerable<Warehouse> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static WarehouseDto ToDto(this Warehouse model)
        {
            return new WarehouseDto
            {
                Id = model.Id,
                Name = model.Name,
                Location = model.Location,
                IsActive = model.IsActive
            };
        }

        public static Warehouse ToEntity(this WarehouseDto model)
        {
            return new Warehouse
            {
                Id = model.Id,
                Name = model.Name,
                Location = model.Location,
                IsActive = model.IsActive
            };
        }
    }
}