//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.IdentityModule.Domain.Entities;
using QuickCode.DemoTest.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.IdentityModule.Persistence.Contexts;
using QuickCode.DemoTest.IdentityModule.Application.Dtos.PortalPageDefinition;
using QuickCode.DemoTest.IdentityModule.Application.Mappings;
using QuickCode.DemoTest.IdentityModule.Persistence.Sql;
using QuickCode.DemoTest.IdentityModule.Domain.Enums;

namespace QuickCode.DemoTest.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageDefinitionRepository : BaseRepository, IPortalPageDefinitionRepository
    {
        public async Task<RepoResponse<List<GetPortalPageDefinitionsWithModuleNameResponseDto>>> GetPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_ModuleName = portalPageDefinitionsModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsWithModuleNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageDefinitionsWithModelNameResponseDto>>> GetPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_ModelName = portalPageDefinitionsModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsWithModelNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling("ExistsPortalPageDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.ExistsPortalPageDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_ModuleName = portalPageDefinitionsModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling("ExistsPortalPageDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.ExistsPortalPageDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_ModelName = portalPageDefinitionsModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>>> GetPortalPageAccessGrantsForPortalPageDefinitionsAsync(string portalPageDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrantsForPortalPageDefinitions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageAccessGrantsForPortalPageDefinitions);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_Key = portalPageDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>> GetPortalPageAccessGrantsForPortalPageDefinitionsDetailsAsync(string portalPageDefinitionsKey, string portalPageAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrantsForPortalPageDefinitionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageAccessGrantsForPortalPageDefinitionsDetails);
                var parameters = new
                {
                    PRM_PortalPageAccessGrants_PermissionGroupName = portalPageAccessGrantsPermissionGroupName,
                    PRM_PortalPageDefinitions_Key = portalPageDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPortalPageAccessGrantsForPortalPageDefinitionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PortalPageDefinition");
            });
        }
    }
}