SELECT [ID], [ORDER_DATE], [TOTAL_AMOUNT], [ORDER_STATUS] 
FROM [ORDERS] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_ORDERS_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 