SELECT OI.[ID], OI.[ORDER_ID], OI.[PRODUCT_ID], OI.[QUANTITY], OI.[PRICE] 
FROM [ORDER_ITEMS] OI 
	INNER JOIN [ORDERS] O 
			ON OI.[ORDER_ID] = O.[ID] 
WHERE OI.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND OI.[ID] = @PRM_ORDER_ITEMS_ID 
	AND O.[ID] = @PRM_ORDERS_ID 
ORDER BY OI.[ID] 