SELECT O.[ID], O.[CUSTOMER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[SHIPPING_ADDRESS_ID], O.[BILLING_ADDRESS_ID], O.[ORDER_STATUS], O.[PAYMENT_STATUS], O.[PAYMENT_METHOD_ID], O.[CREATED_DATE] 
FROM [ORDER_ITEMS] OI 
	INNER JOIN [ORDERS] O 
			ON OI.[ORDER_ID] = O.[ID] 
WHERE OI.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
ORDER BY O.[ID] 