SELECT [ID], [CUSTOMER_ID], [ORDER_DATE], [TOTAL_AMOUNT] 
FROM [ORDERS] 
WHERE [IsDeleted] = 0 
	AND [ORDER_STATUS] = @PRM_ORDERS_ORDER_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 