SELECT [ID], [EXCEPTION_DATE], [EXCEPTION_REASON] 
FROM [DELIVERY_EXCEPTIONS] 
WHERE [IsDeleted] = 0 
	AND [SHIPMENT_ID] = @PRM_DELIVERY_EXCEPTIONS_SHIPMENT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 