SELECT [ID], [TRACKING_NUMBER], [SHIPPING_STATUS] 
FROM [SHIPMENTS] 
WHERE [IsDeleted] = 0 
	AND [ORDER_ID] = @PRM_SHIPMENTS_ORDER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 