SELECT [ID], [ORDER_ID], [TRACKING_NUMBER] 
FROM [SHIPMENTS] 
WHERE [IsDeleted] = 0 
	AND [SHIPPING_STATUS] = @PRM_SHIPMENTS_SHIPPING_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 