SELECT DE.[ID], DE.[SHIPMENT_ID], DE.[EXCEPTION_DATE], DE.[EXCEPTION_REASON] 
FROM [DELIVERY_EXCEPTIONS] DE 
	INNER JOIN [SHIPMENTS] S 
			ON DE.[SHIPMENT_ID] = S.[ID] 
WHERE DE.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND DE.[ID] = @PRM_DELIVERY_EXCEPTIONS_ID 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
ORDER BY DE.[ID] 