SELECT STE.[ID], STE.[SHIPMENT_ID], STE.[EVENT_DATE], STE.[EVENT_LOCATION], STE.[EVENT_DESCRIPTION] 
FROM [SHIPMENT_TRACKING_EVENTS] STE 
	INNER JOIN [SHIPMENTS] S 
			ON STE.[SHIPMENT_ID] = S.[ID] 
WHERE STE.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND STE.[ID] = @PRM_SHIPMENT_TRACKING_EVENTS_ID 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
ORDER BY STE.[ID] 