SELECT S.[ID], S.[ORDER_ID], S.[SHIPPING_CARRIER_ID], S.[TRACKING_NUMBER], S.[SHIPPING_DATE], S.[ESTIMATED_DELIVERY_DATE], S.[ACTUAL_DELIVERY_DATE], S.[SHIPPING_STATUS], S.[SHIPPING_COST], S.[DELIVERY_ADDRESS_ID], S.[CREATED_DATE] 
FROM [SHIPMENT_TRACKING_EVENTS] STE 
	INNER JOIN [SHIPMENTS] S 
			ON STE.[SHIPMENT_ID] = S.[ID] 
WHERE STE.[IsDeleted] = 0 
	AND S.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
ORDER BY S.[ID] 