//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.OrderModule.Domain.Entities;
using QuickCode.DemoTest.OrderModule.Application.Dtos.ShippingAddress;
using System.Threading.Tasks;
using QuickCode.DemoTest.OrderModule.Domain.Enums;

namespace QuickCode.DemoTest.OrderModule.Application.Interfaces.Repositories
{
    public partial interface IShippingAddressRepository : IBaseRepository<ShippingAddressDto>
    {
        Task<RepoResponse<ShippingAddressDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int shippingAddressesCustomerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetOrdersForShippingAddressesResponseDto>>> GetOrdersForShippingAddressesAsync(int shippingAddressesId);
        Task<RepoResponse<GetOrdersForShippingAddressesResponseDto>> GetOrdersForShippingAddressesDetailsAsync(int shippingAddressesId, int ordersId);
    }
}