//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Application.Dtos.DeliveryAddress
{
    public record GetShipmentsForDeliveryAddressesResponseDto
    {
        public int Id { get; init; }
        public int OrderId { get; init; }
        public int ShippingCarrierId { get; init; }
        public string TrackingNumber { get; init; }
        public DateTime ShippingDate { get; init; }
        public DateTime EstimatedDeliveryDate { get; init; }
        public DateTime ActualDeliveryDate { get; init; }
        public ShippingStatus ShippingStatus { get; init; }
        public decimal ShippingCost { get; init; }
        public int DeliveryAddressId { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}