//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.IdentityModule.Domain.Entities;
using QuickCode.DemoTest.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.IdentityModule.Persistence.Contexts;
using QuickCode.DemoTest.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.DemoTest.IdentityModule.Application.Mappings;
using QuickCode.DemoTest.IdentityModule.Persistence.Sql;
using QuickCode.DemoTest.IdentityModule.Domain.Enums;

namespace QuickCode.DemoTest.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModuleNameResponseDto>>> GetApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModuleName = apiMethodDefinitionsModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModuleNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModelNameResponseDto>>> GetApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModelName = apiMethodDefinitionsModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModelNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModuleName = apiMethodDefinitionsModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModelName = apiMethodDefinitionsModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>>> GetApiMethodAccessGrantsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForApiMethodDefinitions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodAccessGrantsForApiMethodDefinitions);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>> GetApiMethodAccessGrantsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string apiMethodAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForApiMethodDefinitionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodAccessGrantsForApiMethodDefinitionsDetails);
                var parameters = new
                {
                    PRM_ApiMethodAccessGrants_PermissionGroupName = apiMethodAccessGrantsPermissionGroupName,
                    PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetKafkaEventsForApiMethodDefinitionsResponseDto>>> GetKafkaEventsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetKafkaEventsForApiMethodDefinitions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetKafkaEventsForApiMethodDefinitions);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetKafkaEventsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<GetKafkaEventsForApiMethodDefinitionsResponseDto>> GetKafkaEventsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string kafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetKafkaEventsForApiMethodDefinitionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetKafkaEventsForApiMethodDefinitionsDetails);
                var parameters = new
                {
                    PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                    PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetKafkaEventsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ApiMethodDefinition");
            });
        }
    }
}