SELECT [ID], [NAME], [DESCRIPTION] 
FROM [PRODUCT_CATEGORIES] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_PRODUCT_CATEGORIES_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 