SELECT [ID], [NAME] 
FROM [PRODUCT_CATEGORIES] 
WHERE [IsDeleted] = 0 
	AND [PARENT_CATEGORY_ID] = @PRM_PRODUCT_CATEGORIES_PARENT_CATEGORY_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 