SELECT P.[ID], P.[NAME], P.[DESCRIPTION], P.[SKU], P.[PRICE], P.[CATEGORY_ID], P.[BRAND_ID], P.[STATUS], P.[VISIBILITY], P.[CREATED_DATE] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_CATEGORIES] PC 
			ON P.[CATEGORY_ID] = PC.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PC.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PRODUCTS_ID 
	AND PC.[ID] = @PRM_PRODUCT_CATEGORIES_ID 
ORDER BY P.[ID] 