SELECT PC.[ID], PC.[NAME], PC.[DESCRIPTION], PC.[PARENT_CATEGORY_ID], PC.[IS_ACTIVE] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_CATEGORIES] PC 
			ON P.[CATEGORY_ID] = PC.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PC.[IsDeleted] = 0 
	AND PC.[ID] = @PRM_PRODUCT_CATEGORIES_ID 
ORDER BY PC.[ID] 