SELECT [ID], [NAME], [DESCRIPTION] 
FROM [PRODUCT_CATEGORIES] 
WHERE [IsDeleted] = 0 
	AND [NAME] LIKE '%' + @PRM_PRODUCT_CATEGORIES_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 