//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.DemoTest.IdentityModule.Domain.Entities;
using QuickCode.DemoTest.IdentityModule.Domain.Enums;

namespace QuickCode.DemoTest.IdentityModule.Application.Mappings
{
    public static class ApiMethodDefinitionMappings
    {
        public static List<ApiMethodDefinitionDto> ToDto(this IEnumerable<ApiMethodDefinition> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ApiMethodDefinitionDto ToDto(this ApiMethodDefinition model)
        {
            return new ApiMethodDefinitionDto
            {
                Key = model.Key,
                ModuleName = model.ModuleName,
                ModelName = model.ModelName,
                HttpMethod = model.HttpMethod,
                ControllerName = model.ControllerName,
                MethodName = model.MethodName,
                UrlPath = model.UrlPath
            };
        }

        public static ApiMethodDefinition ToEntity(this ApiMethodDefinitionDto model)
        {
            return new ApiMethodDefinition
            {
                Key = model.Key,
                ModuleName = model.ModuleName,
                ModelName = model.ModelName,
                HttpMethod = model.HttpMethod,
                ControllerName = model.ControllerName,
                MethodName = model.MethodName,
                UrlPath = model.UrlPath
            };
        }
    }
}