//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.InventoryModule.Domain.Entities;
using QuickCode.DemoTest.InventoryModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.InventoryModule.Persistence.Contexts;
using QuickCode.DemoTest.InventoryModule.Application.Dtos.Stock;
using QuickCode.DemoTest.InventoryModule.Application.Mappings;
using QuickCode.DemoTest.InventoryModule.Persistence.Sql;

namespace QuickCode.DemoTest.InventoryModule.Persistence.Repositories
{
    public partial class StockRepository : BaseRepository, IStockRepository
    {
        public async Task<RepoResponse<int>> AdjustStockAsync(int stocksProductId, int stocksWarehouseId, AdjustStockRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Stock", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Stock.Command.AdjustStock);
                var parameters = new
                {
                    STOCKS_QUANTITY = updateRequest.StocksQuantity,
                    PRM_STOCKS_PRODUCT_ID = stocksProductId,
                    PRM_STOCKS_WAREHOUSE_ID = stocksWarehouseId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}