SELECT [ID], [EVENT_DATE], [EVENT_LOCATION], [EVENT_DESCRIPTION] 
FROM [SHIPMENT_TRACKING_EVENTS] 
WHERE [IsDeleted] = 0 
	AND [SHIPMENT_ID] = @PRM_SHIPMENT_TRACKING_EVENTS_SHIPMENT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 