//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Application.Dtos.ShippingRate
{
    public record GetByCarrierAndZipResponseDto
    {
        public int Id { get; init; }
        public decimal WeightFrom { get; init; }
        public decimal WeightTo { get; init; }
        public decimal Rate { get; init; }
    }
}