SELECT [ID], [PAYMENT_TYPE] 
FROM [PAYMENT_METHODS] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_PAYMENT_METHODS_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 