SELECT O.[ID], O.[CUSTOMER_ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[SHIPPING_ADDRESS_ID], O.[BILLING_ADDRESS_ID], O.[ORDER_STATUS], O.[PAYMENT_STATUS], O.[PAYMENT_METHOD_ID], O.[CREATED_DATE] 
FROM [ORDERS] O 
	INNER JOIN [PAYMENT_METHODS] PM 
			ON O.[PAYMENT_METHOD_ID] = PM.[ID] 
WHERE O.[IsDeleted] = 0 
	AND PM.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND PM.[ID] = @PRM_PAYMENT_METHODS_ID 
ORDER BY O.[ID] 