SELECT PM.[ID], PM.[CUSTOMER_ID], PM.[CARD_NUMBER], PM.[EXPIRY_DATE], PM.[CVV], PM.[PAYMENT_TYPE] 
FROM [ORDERS] O 
	INNER JOIN [PAYMENT_METHODS] PM 
			ON O.[PAYMENT_METHOD_ID] = PM.[ID] 
WHERE O.[IsDeleted] = 0 
	AND PM.[IsDeleted] = 0 
	AND PM.[ID] = @PRM_PAYMENT_METHODS_ID 
ORDER BY PM.[ID] 