SELECT [ID], [WAREHOUSE_ID], [REORDER_QUANTITY], [MINIMUM_STOCK_LEVEL] 
FROM [REORDER_POINTS] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_REORDER_POINTS_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 