//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ShippingModule.Persistence.Contexts;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.ShipmentTrackingEvent;
using QuickCode.DemoTest.ShippingModule.Application.Mappings;
using QuickCode.DemoTest.ShippingModule.Persistence.Sql;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Persistence.Repositories
{
    public partial class ShipmentTrackingEventRepository : BaseRepository, IShipmentTrackingEventRepository
    {
        public async Task<RepoResponse<List<GetByShipmentResponseDto>>> GetByShipmentAsync(int shipmentTrackingEventsShipmentId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByShipment", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByShipmentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ShipmentTrackingEvent.Query.GetByShipment);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SHIPMENT_TRACKING_EVENTS_SHIPMENT_ID = shipmentTrackingEventsShipmentId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByShipmentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ShipmentTrackingEvent");
                }
            });
        }
    }
}