//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.ShippingModule.Persistence.Contexts;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.DeliveryAddress;
using QuickCode.DemoTest.ShippingModule.Application.Mappings;
using QuickCode.DemoTest.ShippingModule.Persistence.Sql;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Persistence.Repositories
{
    public partial class DeliveryAddressRepository : BaseRepository, IDeliveryAddressRepository
    {
        public async Task<RepoResponse<List<GetByCustomerResponseDto>>> GetByCustomerAsync(int deliveryAddressesCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByCustomer", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.DeliveryAddress.Query.GetByCustomer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_DELIVERY_ADDRESSES_CUSTOMER_ID = deliveryAddressesCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByCustomerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in DeliveryAddress");
                }
            });
        }

        public async Task<RepoResponse<List<GetShipmentsForDeliveryAddressesResponseDto>>> GetShipmentsForDeliveryAddressesAsync(int deliveryAddressesId)
        {
            return await ExecuteWithExceptionHandling("GetShipmentsForDeliveryAddresses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.DeliveryAddress.Query.GetShipmentsForDeliveryAddresses);
                var parameters = new
                {
                    PRM_DELIVERY_ADDRESSES_ID = deliveryAddressesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetShipmentsForDeliveryAddressesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in DeliveryAddress");
            });
        }

        public async Task<RepoResponse<GetShipmentsForDeliveryAddressesResponseDto>> GetShipmentsForDeliveryAddressesDetailsAsync(int deliveryAddressesId, int shipmentsId)
        {
            return await ExecuteWithExceptionHandling("GetShipmentsForDeliveryAddressesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.DeliveryAddress.Query.GetShipmentsForDeliveryAddressesDetails);
                var parameters = new
                {
                    PRM_SHIPMENTS_ID = shipmentsId,
                    PRM_DELIVERY_ADDRESSES_ID = deliveryAddressesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetShipmentsForDeliveryAddressesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in DeliveryAddress");
            });
        }
    }
}