SELECT [ID], [IMAGE_URL], [IS_PRIMARY] 
FROM [PRODUCT_IMAGES] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_PRODUCT_IMAGES_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 