SELECT [ID], [PRODUCT_ID], [QUANTITY], [PRICE] 
FROM [ORDER_ITEMS] 
WHERE [IsDeleted] = 0 
	AND [ORDER_ID] = @PRM_ORDER_ITEMS_ORDER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 