SELECT [ID], [ADDRESS_LINE_1], [ADDRESS_LINE_2], [CITY], [STATE], [ZIP_CODE], [COUNTRY] 
FROM [SHIPPING_ADDRESSES] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_SHIPPING_ADDRESSES_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 