SELECT SA.[ID], SA.[CUSTOMER_ID], SA.[ADDRESS_LINE_1], SA.[ADDRESS_LINE_2], SA.[CITY], SA.[STATE], SA.[ZIP_CODE], SA.[COUNTRY] 
FROM [ORDERS] O 
	INNER JOIN [SHIPPING_ADDRESSES] SA 
			ON O.[SHIPPING_ADDRESS_ID] = SA.[ID] 
WHERE O.[IsDeleted] = 0 
	AND SA.[IsDeleted] = 0 
	AND SA.[ID] = @PRM_SHIPPING_ADDRESSES_ID 
ORDER BY SA.[ID] 