//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.ShippingModule.Persistence.Contexts;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.ShippingCarrier;
using QuickCode.DemoTest.ShippingModule.Application.Mappings;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Persistence.Repositories
{
    public partial class ShippingCarrierRepository : BaseRepository, IShippingCarrierRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public ShippingCarrierRepository(ILogger<ShippingCarrierRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "ShippingCarrier")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<ShippingCarrierDto>> InsertAsync(ShippingCarrierDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.ShippingCarrier.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<ShippingCarrierDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ShippingCarrierDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.ShippingCarrier>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ShippingCarrierDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.ShippingCarrier.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<ShippingCarrierDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from shipping_carrier in _readContext.ShippingCarrier
                    where shipping_carrier.Id.Equals(id)
                    select shipping_carrier;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<ShippingCarrierDto>
                {
                    Code = 404,
                    Message = "Not found in ShippingCarrier"
                }

                : new RepoResponse<ShippingCarrierDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<ShippingCarrierDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ShippingCarrierDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.ShippingCarrier.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<ShippingCarrierDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.ShippingCarrier.CountAsync(), "Success");
            });
        }
    }
}