//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductReview
{
    public record ProductReviewDto
    {
        public int Id { get; init; }
        public int ProductId { get; init; }
        public int UserId { get; init; }
        public short Rating { get; init; }
        public string Comment { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}