//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.Product;
using System.Threading.Tasks;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IProductRepository : IBaseRepository<ProductDto>
    {
        Task<RepoResponse<ProductDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(ProductStatus productsStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string productsName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCategoryResponseDto>>> GetByCategoryAsync(int productsCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByPriceRangeResponseDto>>> GetByPriceRangeAsync(decimal productsPrice, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetNewestResponseDto>>> GetNewestAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetProductImagesForProductsResponseDto>>> GetProductImagesForProductsAsync(int productsId);
        Task<RepoResponse<GetProductImagesForProductsResponseDto>> GetProductImagesForProductsDetailsAsync(int productsId, int productImagesId);
        Task<RepoResponse<List<GetProductReviewsForProductsResponseDto>>> GetProductReviewsForProductsAsync(int productsId);
        Task<RepoResponse<GetProductReviewsForProductsResponseDto>> GetProductReviewsForProductsDetailsAsync(int productsId, int productReviewsId);
        Task<RepoResponse<List<GetProductSpecificationsForProductsResponseDto>>> GetProductSpecificationsForProductsAsync(int productsId);
        Task<RepoResponse<GetProductSpecificationsForProductsResponseDto>> GetProductSpecificationsForProductsDetailsAsync(int productsId, int productSpecificationsId);
        Task<RepoResponse<int>> UpdatePriceAsync(int productsId, UpdatePriceRequestDto updateRequest);
    }
}