//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductImage;
using System.Threading.Tasks;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IProductImageRepository : IBaseRepository<ProductImageDto>
    {
        Task<RepoResponse<ProductImageDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByProductResponseDto>>> GetByProductAsync(int productImagesProductId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> SetPrimaryAsync(int productImagesId, SetPrimaryRequestDto updateRequest);
    }
}