//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductBrand;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Mappings
{
    public static class ProductBrandMappings
    {
        public static List<ProductBrandDto> ToDto(this IEnumerable<ProductBrand> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductBrandDto ToDto(this ProductBrand model)
        {
            return new ProductBrandDto
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }

        public static ProductBrand ToEntity(this ProductBrandDto model)
        {
            return new ProductBrand
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }
    }
}