//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductReview;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Mappings
{
    public static class ProductReviewMappings
    {
        public static List<ProductReviewDto> ToDto(this IEnumerable<ProductReview> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductReviewDto ToDto(this ProductReview model)
        {
            return new ProductReviewDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                UserId = model.UserId,
                Rating = model.Rating,
                Comment = model.Comment,
                CreatedDate = model.CreatedDate
            };
        }

        public static ProductReview ToEntity(this ProductReviewDto model)
        {
            return new ProductReview
            {
                Id = model.Id,
                ProductId = model.ProductId,
                UserId = model.UserId,
                Rating = model.Rating,
                Comment = model.Comment,
                CreatedDate = model.CreatedDate
            };
        }
    }
}