//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.ProductImage;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Mappings
{
    public static class ProductImageMappings
    {
        public static List<ProductImageDto> ToDto(this IEnumerable<ProductImage> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductImageDto ToDto(this ProductImage model)
        {
            return new ProductImageDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                ImageUrl = model.ImageUrl,
                IsPrimary = model.IsPrimary
            };
        }

        public static ProductImage ToEntity(this ProductImageDto model)
        {
            return new ProductImage
            {
                Id = model.Id,
                ProductId = model.ProductId,
                ImageUrl = model.ImageUrl,
                IsPrimary = model.IsPrimary
            };
        }
    }
}