//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ProductCatalogModule.Application.Dtos.Product;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoTest.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoTest.ProductCatalogModule.Application.Mappings
{
    public static class ProductMappings
    {
        public static List<ProductDto> ToDto(this IEnumerable<Product> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductDto ToDto(this Product model)
        {
            return new ProductDto
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Sku = model.Sku,
                Price = model.Price,
                CategoryId = model.CategoryId,
                BrandId = model.BrandId,
                Status = model.Status,
                Visibility = model.Visibility,
                CreatedDate = model.CreatedDate
            };
        }

        public static Product ToEntity(this ProductDto model)
        {
            return new Product
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Sku = model.Sku,
                Price = model.Price,
                CategoryId = model.CategoryId,
                BrandId = model.BrandId,
                Status = model.Status,
                Visibility = model.Visibility,
                CreatedDate = model.CreatedDate
            };
        }
    }
}