SELECT S.[ID], S.[ORDER_ID], S.[SHIPPING_CARRIER_ID], S.[TRACKING_NUMBER], S.[SHIPPING_DATE], S.[ESTIMATED_DELIVERY_DATE], S.[ACTUAL_DELIVERY_DATE], S.[SHIPPING_STATUS], S.[SHIPPING_COST], S.[DELIVERY_ADDRESS_ID], S.[CREATED_DATE] 
FROM [SHIPMENTS] S 
	INNER JOIN [SHIPPING_CARRIERS] SC 
			ON S.[SHIPPING_CARRIER_ID] = SC.[ID] 
WHERE S.[IsDeleted] = 0 
	AND SC.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
	AND SC.[ID] = @PRM_SHIPPING_CARRIERS_ID 
ORDER BY S.[ID] 