SELECT SC.[ID], SC.[NAME], SC.[TRACKING_URL_FORMAT], SC.[IS_ACTIVE] 
FROM [SHIPMENTS] S 
	INNER JOIN [SHIPPING_CARRIERS] SC 
			ON S.[SHIPPING_CARRIER_ID] = SC.[ID] 
WHERE S.[IsDeleted] = 0 
	AND SC.[IsDeleted] = 0 
	AND SC.[ID] = @PRM_SHIPPING_CARRIERS_ID 
ORDER BY SC.[ID] 