//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.InventoryModule.Domain.Entities;
using QuickCode.DemoTest.InventoryModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoTest.Common;
using QuickCode.DemoTest.Common.Extensions;
using QuickCode.DemoTest.Common.Helpers;
using QuickCode.DemoTest.InventoryModule.Persistence.Contexts;
using QuickCode.DemoTest.InventoryModule.Application.Dtos.Warehouse;
using QuickCode.DemoTest.InventoryModule.Application.Mappings;
using QuickCode.DemoTest.InventoryModule.Persistence.Sql;

namespace QuickCode.DemoTest.InventoryModule.Persistence.Repositories
{
    public partial class WarehouseRepository : BaseRepository, IWarehouseRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool warehousesIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_WAREHOUSES_IS_ACTIVE = warehousesIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Warehouse");
                }
            });
        }

        public async Task<RepoResponse<List<GetStocksForWarehousesResponseDto>>> GetStocksForWarehousesAsync(int warehousesId)
        {
            return await ExecuteWithExceptionHandling("GetStocksForWarehouses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetStocksForWarehouses);
                var parameters = new
                {
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetStocksForWarehousesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<GetStocksForWarehousesResponseDto>> GetStocksForWarehousesDetailsAsync(int warehousesId, int stocksId)
        {
            return await ExecuteWithExceptionHandling("GetStocksForWarehousesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetStocksForWarehousesDetails);
                var parameters = new
                {
                    PRM_STOCKS_ID = stocksId,
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetStocksForWarehousesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<List<GetStockMovementsForWarehousesResponseDto>>> GetStockMovementsForWarehousesAsync(int warehousesId)
        {
            return await ExecuteWithExceptionHandling("GetStockMovementsForWarehouses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetStockMovementsForWarehouses);
                var parameters = new
                {
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetStockMovementsForWarehousesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<GetStockMovementsForWarehousesResponseDto>> GetStockMovementsForWarehousesDetailsAsync(int warehousesId, int stockMovementsId)
        {
            return await ExecuteWithExceptionHandling("GetStockMovementsForWarehousesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetStockMovementsForWarehousesDetails);
                var parameters = new
                {
                    PRM_STOCK_MOVEMENTS_ID = stockMovementsId,
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetStockMovementsForWarehousesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<List<GetReorderPointsForWarehousesResponseDto>>> GetReorderPointsForWarehousesAsync(int warehousesId)
        {
            return await ExecuteWithExceptionHandling("GetReorderPointsForWarehouses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetReorderPointsForWarehouses);
                var parameters = new
                {
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetReorderPointsForWarehousesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<GetReorderPointsForWarehousesResponseDto>> GetReorderPointsForWarehousesDetailsAsync(int warehousesId, int reorderPointsId)
        {
            return await ExecuteWithExceptionHandling("GetReorderPointsForWarehousesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetReorderPointsForWarehousesDetails);
                var parameters = new
                {
                    PRM_REORDER_POINTS_ID = reorderPointsId,
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetReorderPointsForWarehousesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<List<GetInventoryAdjustmentsForWarehousesResponseDto>>> GetInventoryAdjustmentsForWarehousesAsync(int warehousesId)
        {
            return await ExecuteWithExceptionHandling("GetInventoryAdjustmentsForWarehouses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetInventoryAdjustmentsForWarehouses);
                var parameters = new
                {
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetInventoryAdjustmentsForWarehousesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Warehouse");
            });
        }

        public async Task<RepoResponse<GetInventoryAdjustmentsForWarehousesResponseDto>> GetInventoryAdjustmentsForWarehousesDetailsAsync(int warehousesId, int inventoryAdjustmentsId)
        {
            return await ExecuteWithExceptionHandling("GetInventoryAdjustmentsForWarehousesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Warehouse.Query.GetInventoryAdjustmentsForWarehousesDetails);
                var parameters = new
                {
                    PRM_INVENTORY_ADJUSTMENTS_ID = inventoryAdjustmentsId,
                    PRM_WAREHOUSES_ID = warehousesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetInventoryAdjustmentsForWarehousesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Warehouse");
            });
        }
    }
}