SELECT [ID], [SPECIFICATION_KEY], [SPECIFICATION_VALUE] 
FROM [PRODUCT_SPECIFICATIONS] 
WHERE [IsDeleted] = 0 
	AND [PRODUCT_ID] = @PRM_PRODUCT_SPECIFICATIONS_PRODUCT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 