SELECT DA.[ID], DA.[CUSTOMER_ID], DA.[ADDRESS_LINE_1], DA.[ADDRESS_LINE_2], DA.[CITY], DA.[STATE], DA.[ZIP_CODE], DA.[COUNTRY] 
FROM [SHIPMENTS] S 
	INNER JOIN [DELIVERY_ADDRESSES] DA 
			ON S.[DELIVERY_ADDRESS_ID] = DA.[ID] 
WHERE S.[IsDeleted] = 0 
	AND DA.[IsDeleted] = 0 
	AND DA.[ID] = @PRM_DELIVERY_ADDRESSES_ID 
ORDER BY DA.[ID] 