SELECT S.[ID], S.[ORDER_ID], S.[SHIPPING_CARRIER_ID], S.[TRACKING_NUMBER], S.[SHIPPING_DATE], S.[ESTIMATED_DELIVERY_DATE], S.[ACTUAL_DELIVERY_DATE], S.[SHIPPING_STATUS], S.[SHIPPING_COST], S.[DELIVERY_ADDRESS_ID], S.[CREATED_DATE] 
FROM [SHIPMENTS] S 
	INNER JOIN [DELIVERY_ADDRESSES] DA 
			ON S.[DELIVERY_ADDRESS_ID] = DA.[ID] 
WHERE S.[IsDeleted] = 0 
	AND DA.[IsDeleted] = 0 
	AND S.[ID] = @PRM_SHIPMENTS_ID 
	AND DA.[ID] = @PRM_DELIVERY_ADDRESSES_ID 
ORDER BY S.[ID] 