//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.Shipment;
using System.Threading.Tasks;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories
{
    public partial interface IShipmentRepository : IBaseRepository<ShipmentDto>
    {
        Task<RepoResponse<ShipmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByOrderResponseDto>>> GetByOrderAsync(int shipmentsOrderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ShippingStatus shipmentsShippingStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetShipmentTrackingEventsForShipmentsResponseDto>>> GetShipmentTrackingEventsForShipmentsAsync(int shipmentsId);
        Task<RepoResponse<GetShipmentTrackingEventsForShipmentsResponseDto>> GetShipmentTrackingEventsForShipmentsDetailsAsync(int shipmentsId, int shipmentTrackingEventsId);
        Task<RepoResponse<List<GetDeliveryExceptionsForShipmentsResponseDto>>> GetDeliveryExceptionsForShipmentsAsync(int shipmentsId);
        Task<RepoResponse<GetDeliveryExceptionsForShipmentsResponseDto>> GetDeliveryExceptionsForShipmentsDetailsAsync(int shipmentsId, int deliveryExceptionsId);
        Task<RepoResponse<int>> UpdateStatusAsync(int shipmentsId, UpdateStatusRequestDto updateRequest);
    }
}