//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoTest.Common.Models;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.ShippingCarrier;
using System.Threading.Tasks;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Application.Interfaces.Repositories
{
    public partial interface IShippingCarrierRepository : IBaseRepository<ShippingCarrierDto>
    {
        Task<RepoResponse<ShippingCarrierDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool shippingCarriersIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetShipmentsForShippingCarriersResponseDto>>> GetShipmentsForShippingCarriersAsync(int shippingCarriersId);
        Task<RepoResponse<GetShipmentsForShippingCarriersResponseDto>> GetShipmentsForShippingCarriersDetailsAsync(int shippingCarriersId, int shipmentsId);
    }
}