//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoTest.ShippingModule.Application.Dtos.ShipmentTrackingEvent;
using QuickCode.DemoTest.ShippingModule.Domain.Entities;
using QuickCode.DemoTest.ShippingModule.Domain.Enums;

namespace QuickCode.DemoTest.ShippingModule.Application.Mappings
{
    public static class ShipmentTrackingEventMappings
    {
        public static List<ShipmentTrackingEventDto> ToDto(this IEnumerable<ShipmentTrackingEvent> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ShipmentTrackingEventDto ToDto(this ShipmentTrackingEvent model)
        {
            return new ShipmentTrackingEventDto
            {
                Id = model.Id,
                ShipmentId = model.ShipmentId,
                EventDate = model.EventDate,
                EventLocation = model.EventLocation,
                EventDescription = model.EventDescription
            };
        }

        public static ShipmentTrackingEvent ToEntity(this ShipmentTrackingEventDto model)
        {
            return new ShipmentTrackingEvent
            {
                Id = model.Id,
                ShipmentId = model.ShipmentId,
                EventDate = model.EventDate,
                EventLocation = model.EventLocation,
                EventDescription = model.EventDescription
            };
        }
    }
}